version: "3"
services:
  test-db:
    image: postgres
    container_name: postgres-test-db
    volumes:
      - db
    env_file:
      - database.env
    expose:
      - 5432
    ports:
    - 5432:5432
    restart: always
  test-service:
    image: test-app
    container_name: test-service
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    expose:
      - 8183
    ports:
    - 8183:8183
    restart: always
    depends_on:
      - test-db
volumes:
  db: